# Generated by Django 5.1.1 on 2024-12-22 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dentist",
            name="dentistName",
        ),
    ]
