# Generated by Django 5.1.1 on 2024-12-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0002_remove_dentist_dentistname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="ผู้จัดการ"),
        ),
    ]
