# Generated by Django 5.1.1 on 2024-12-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0004_remove_dentist_d_email_remove_dentist_d_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmenthistory",
            name="status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
