# Generated by Django 5.1.1 on 2024-12-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0005_alter_treatmenthistory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmenthistory",
            name="status",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
