# Generated by Django 5.1.1 on 2024-12-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0006_alter_treatmenthistory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="is_braces",
            field=models.BooleanField(
                default=False, verbose_name="เป็นการจัดฟันหรือไม่"
            ),
        ),
    ]
