# Generated by Django 5.1.1 on 2025-01-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0010_extra_treatmenthistory_extra"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Sparky.dentist"
                    ),
                ),
            ],
        ),
    ]
