# Generated by Django 5.1.1 on 2025-01-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0011_closedday"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="closedday",
            constraint=models.UniqueConstraint(
                fields=("dentist", "date"), name="unique_dentist_date"
            ),
        ),
    ]
