# Generated by Django 5.1.1 on 2025-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0012_closedday_unique_dentist_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allergic_symptoms",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="อาการแพ้ยา"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ud_symptoms",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="อาการโรคประจำตัว"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, verbose_name="พนักงานหน้าเคาน์เตอร์"
            ),
        ),
    ]
