# Generated by Django 5.1.1 on 2025-02-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0013_profile_allergic_symptoms_profile_ud_symptoms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="idCard",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="เลขประจำตัวประชาชน"
            ),
        ),
    ]
