# Generated by Django 5.1.1 on 2025-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0014_alter_profile_idcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="ที่อยู่"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthDate",
            field=models.DateField(blank=True, null=True, verbose_name="วันเกิด"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("ชาย", "ชาย"), ("หญิง", "หญิง")],
                default="ชาย",
                max_length=10,
                null=True,
                verbose_name="เพศ",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="เบอร์โทรศัพท์มือถือ"
            ),
        ),
    ]
