# Generated by Django 5.1.1 on 2025-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0015_alter_profile_address_alter_profile_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="idCard",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                verbose_name="เลขประจำตัวประชาชน",
            ),
        ),
    ]
