# Generated by Django 5.1.1 on 2025-03-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sparky", "0016_alter_profile_idcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="เจ้าของคลินิก"),
        ),
    ]
