services:
  web:
    build: .
    ports:
      - "${WEB_PORT1}:${WEB_PORT2}"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - app_network   # ใช้ network ร่วมกับ db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app_network   # ใช้ network ร่วมกับ web
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: