services:
  web:
    build: .
    ports:
      - "10295:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "20295:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: