entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
providers:
  docker:
    exposedByDefault: false # ????????????? Traefik ????????? Container ????????????????

# ?????????? Dashboard (???????????? port 8080)
api:
  dashboard: true
  insecure: true # ???????????????????

# ???????????? SSL Certificate ????????? (Let's Encrypt)
certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com # ??????????????
      storage: /acme.json
      httpChallenge:
        entryPoint: web