# Generated by Django 5.1.1 on 2024-12-05 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dentist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dentistName",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อทันตแพทย์"
                    ),
                ),
                (
                    "d_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="อีเมล"
                    ),
                ),
                (
                    "d_phone",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="เบอร์โทรศัพท์มือถือ"
                    ),
                ),
                (
                    "workDays",
                    models.CharField(
                        default="1,2,3,4,5", max_length=50, verbose_name="วันทำงาน"
                    ),
                ),
                (
                    "startTime",
                    models.TimeField(
                        default=datetime.time(9, 0), verbose_name="เวลาเริ่มทำงาน"
                    ),
                ),
                (
                    "endTime",
                    models.TimeField(
                        default=datetime.time(18, 0), verbose_name="เวลาเริ่มทำงาน"
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatmentName",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ประเภทการรักษา"
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
